name: CI

on: [push]

jobs:
  mac-build:

    runs-on: macOS-latest
    
    needs: windows-build
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  windows-build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        rem "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin;%PATH%
        rem echo %PATH%
        rem msbuild NGraphics.sln
        msbuild /t:Restore NGraphics\NGraphics.csproj
        msbuild NGraphics\NGraphics.csproj
        msbuild Platforms\NGraphics.Net\NGraphics.Net.csproj
