name: CI

on: [push]

jobs:
  mac-build:

    runs-on: macOS-latest
    
    needs: windows-build
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  windows-build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set environment
      run: |
        set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin;%PATH%        
        echo %PATH%
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild"
    - name: Build
      run: msbuild NGraphics.sln
